services:
  papermc:
    build: .
    ports:
      - "${EXTERNAL_PORT}:25565"
    volumes:
      - .:/server
    env_file:
      - .env
    stdin_open: true
    tty: true
    restart: on-failure
    container_name: ${CONTAINER_NAME}
    user: "1000:1000"  # Replace with the correct UID:GID
