services:
  papermc:
    build: .
    ports:
      - "25565:${EXTERNAL_PORT}"
    volumes:
      - .:/server
    env_file:
      - .env
    stdin_open: true
    tty: true
    restart: unless-stopped
    container_name: ${CONTAINER_NAME}
    user: "1000:1000"  # Replace with the correct UID:GID
